<?php
namespace links\secciones;
use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use stdClass;

class link_nom_percepcion extends links_menu {
    public stdClass $links;

    private function link_aplica_subsidio(int $registro_id): array|string
    {
        $valida = $this->aplica_subsidio(registro_id: $registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener link de aplica_subsidio',
                data: $valida);
        }

        $valida.="&session_id=$this->session_id";
        return $valida;
    }

    protected function links(int $registro_id): stdClass|array
    {

        $links =  parent::links(registro_id: $registro_id); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al generar links', data: $links);
        }

        $valida = $this->link_aplica_subsidio(registro_id: $registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al generar link', data: $valida);
        }
        $this->links->nom_percepcion->aplica_subsidio = $valida;

        return $links;
    }

    private function aplica_subsidio(int $registro_id): string
    {
        return "./index.php?seccion=nom_percepcion&accion=cambiar_estado_subsidio&registro_id=$registro_id";
    }

}
