<?php /** @var  \gamboamartin\nomina\controllers\controlador_nom_nomina $controlador  controlador en ejecucion */ ?>
<?php use config\views; ?>
<?php echo $controlador->inputs->id; ?>
<?php echo $controlador->inputs->codigo; ?>
<?php echo $controlador->inputs->codigo_bis; ?>
<?php echo $controlador->inputs->descripcion; ?>
<?php echo $controlador->inputs->descripcion_select; ?>
<?php echo $controlador->inputs->alias; ?>
<?php echo $controlador->inputs->select->im_registro_patronal_id; ?>
<?php echo $controlador->inputs->select->em_empleado_id; ?>
<?php echo $controlador->inputs->select->em_cuenta_bancaria_id; ?>
<?php echo $controlador->inputs->rfc; ?>
<?php echo $controlador->inputs->curp; ?>
<?php echo $controlador->inputs->nss; ?>
<?php echo $controlador->inputs->folio; ?>
<?php echo $controlador->inputs->fecha; ?>
<?php echo $controlador->inputs->fecha_inicio_rel_laboral; ?>
<?php echo $controlador->inputs->select->cat_sat_tipo_nomina_id; ?>
<?php echo $controlador->inputs->select->cat_sat_periodicidad_pago_nom_id; ?>
<?php echo $controlador->inputs->fecha_pago; ?>
<?php echo $controlador->inputs->fecha_inicial_pago; ?>
<?php echo $controlador->inputs->fecha_final_pago; ?>
<?php echo $controlador->inputs->num_dias_pagados; ?>
<?php echo $controlador->inputs->salario_diario; ?>
<?php echo $controlador->inputs->salario_diario_integrado; ?>
<?php echo $controlador->inputs->subtotal; ?>
<?php include (new views())->ruta_templates.'botons/submit/alta_bd_otro.php';?>