<?php
namespace gamboamartin\nomina\models;
use base\orm\modelo;

use gamboamartin\comercial\models\com_sucursal;
use gamboamartin\empleado\models\em_empleado;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class nom_rel_empleado_sucursal extends modelo{

    public function __construct(PDO $link){
        $tabla = 'nom_rel_empleado_sucursal';
        $columnas = array($tabla=>false,'em_empleado'=>$tabla,'com_sucursal'=>$tabla);
        $campos_obligatorios = array('em_empleado_id','com_sucursal_id');

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|stdClass
    {

        $em_empleado = (new em_empleado($this->link))->registro(
            registro_id: $this->registro['em_empleado_id'], columnas_en_bruto: true, retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $em_empleado);
        }
        $com_sucursal = (new com_sucursal($this->link))->registro(
            registro_id: $this->registro['com_sucursal_id'], columnas_en_bruto: true, retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $com_sucursal);
        }

        if(!isset($this->registro['codigo'])){
            $codigo = $em_empleado->codigo.' '.$com_sucursal->codigo;
            $this->registro['codigo'] = $codigo;
        }
        if(!isset($this->registro['descripcion'])){
            $descripcion = $em_empleado->rfc.' '.$com_sucursal->codigo;
            $this->registro['descripcion'] = $descripcion;
        }
        if(!isset($this->registro['codigo_bis'])){

            $this->registro['codigo_bis'] = strtoupper($this->registro['codigo']);
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }
}