<?php
namespace models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class nom_conf_percepcion extends modelo{

    public function __construct(PDO $link){
        $tabla = __CLASS__;
        $columnas = array($tabla=>false , "nom_percepcion" => $tabla,"nom_conf_nomina" => $tabla);
        $campos_obligatorios = array('codigo_bis','descripcion_select','alias','nom_conf_nomina_id','nom_percepcion_id');
        $campos_view = array("nom_conf_nomina_id" => array("type" => "selects", "model" => new nom_conf_nomina(link: $link)),
            "nom_percepcion_id" => array("type" => "selects", "model" => new nom_percepcion(link: $link)));

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas,campos_view: $campos_view);
    }

    public function alta_bd(): array|stdClass
    {
        if(!isset($this->registro['codigo_bis'])){
            $this->registro['codigo_bis'] = strtoupper($this->registro['codigo']);
        }

        if(!isset($this->registro['descripcion_select'])){
            $this->registro['descripcion_select'] = $this->registro['descripcion'];
            $this->registro['descripcion_select'] .= $this->registro['codigo'];
        }
        if(!isset($this->registro['alias'])){
            $this->registro['alias'] = strtoupper($this->registro['descripcion_select']);
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta configuracion',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    /**
     * Verifica si aplica septimo dia
     * @param int $nom_conf_nomina_id Configuracion de nomina
     * @return array|bool
     * @version 0.483.26
     */
    public function aplica_septimo_dia(int $nom_conf_nomina_id): array|bool
    {
        if($nom_conf_nomina_id<=0){
            return $this->error->error(
                mensaje: 'Error nom_conf_nomina_id debe ser mayor a 0', data: $nom_conf_nomina_id);
        }
        $filtro['nom_conf_nomina.id'] = $nom_conf_nomina_id;
        $filtro['nom_percepcion.aplica_septimo_dia'] = "activo";

        $existe = $this->existe(filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al determinar si aplica septimo dia', data: $existe);
        }

        return $existe;
    }
}