<?php
namespace gamboamartin\nomina\models;
use base\orm\modelo;
use gamboamartin\documento\models\doc_documento;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class nom_docs extends modelo{

    public function __construct(PDO $link){
        $tabla = 'nom_docs';
        $columnas = array($tabla=>false,'nom_nomina'=>$tabla,'em_empleado'=>'nom_nomina',
            'im_registro_patronal'=>'nom_nomina','nom_periodo'=>'nom_nomina','fc_csd'=>'im_registro_patronal',
            'org_sucursal'=>'fc_csd','org_empresa'=>'org_sucursal','doc_documento'=>'doc_tipo_documento',
            'doc_extension'=>'doc_documento');

        $campos_obligatorios = array('descripcion','codigo','descripcion_select','alias','codigo_bis','nom_nomina_id',
            'doc_documento_id');

        $tipo_campos = array();
        $tipo_campos['nom_nomina_id'] = 'id';
        $tipo_campos['doc_documento_id'] = 'id';

        $campos_view = array();

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, tipo_campos: $tipo_campos);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|stdClass
    {

        $keys = array('doc_documento_id','nom_nomina_id');
        $valida = $this->validacion->valida_ids(keys: $keys, registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro', data:$valida);
        }

        $doc_documento_id = $this->registro['doc_documento_id'];
        $doc_documento = (new doc_documento($this->link))->registro(registro_id: $doc_documento_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener doc_documento', data:$doc_documento);
        }

        $nom_nomina_id = $this->registro['nom_nomina_id'];
        $nom_nomina = (new nom_nomina($this->link))->registro(registro_id: $nom_nomina_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener nom_nomina', data:$nom_nomina);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $doc_documento['doc_tipo_documento_descripcion'].' '.$nom_nomina['nom_nomina_folio'];
            $this->registro['descripcion'] = $descripcion;
        }
        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar nom_docs', data:$r_alta_bd);
        }
        return $r_alta_bd;
    }
}