<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\nomina\controllers;

use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template\html;
use html\cat_sat_moneda_html;
use html\com_cliente_html;
use html\com_producto_html;
use html\com_sucursal_html;
use html\em_empleado_html;
use html\nom_conf_factura_html;
use html\nom_percepcion_html;
use models\com_cliente;
use models\com_producto;
use models\com_sucursal;
use models\em_empleado;
use models\nom_conf_factura;
use models\nom_percepcion;
use PDO;
use stdClass;

class controlador_nom_conf_factura extends system {

    public array $keys_selects = array();

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new nom_conf_factura(link: $link);
        $html_ = new nom_conf_factura_html(html: $html);
        $obj_link = new links_menu(link: $link,registro_id: $this->registro_id);
        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Configuracion Factura';

        $this->asignar_propiedad(identificador: 'cat_sat_forma_pago_id', propiedades: ["label" => "Forma Pago"]);
        $this->asignar_propiedad(identificador: 'cat_sat_metodo_pago_id', propiedades: ["label" => "Metodo Pago"]);
        $this->asignar_propiedad(identificador: 'cat_sat_moneda_id', propiedades: ["label" => "Moneda"]);
        $this->asignar_propiedad(identificador: 'com_tipo_cambio_id', propiedades: ["label" => "Tipo Cambio"]);
        $this->asignar_propiedad(identificador: 'cat_sat_uso_cfdi_id', propiedades: ["label" => "CFDI"]);
        $this->asignar_propiedad(identificador: 'cat_sat_tipo_de_comprobante_id', propiedades: ["label" => "Tipo Comprobante"]);
        $this->asignar_propiedad(identificador: 'com_producto_id', propiedades: ["label" => "Producto"]);

        $btns = (new nom_conf_factura_html(html: $this->html_base))->btns_views();

        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar botones',data:  $btns);
            print_r($error);
            exit;
        }

        $this->btns = $btns;

        $this->total_items_sections = 1;

        $this->actions_number['lista']['item'] = 1;
        $this->actions_number['lista']['etiqueta'] = 'Nueva Configuracion';

        $this->actions_number['alta']['item'] = 1;
        $this->actions_number['alta']['etiqueta'] = 'Nueva Configuracion';

        $this->actions_number['modifica']['item'] = 1;
        $this->actions_number['modifica']['etiqueta'] = 'Nueva Configuracion';


        if(isset($this->actions_number[$this->accion])){
            $this->number_active = $this->actions_number[$this->accion]['item'];
        }
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:$ws);
        }

        $inputs = $this->genera_inputs(keys_selects: $this->keys_selects);
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar inputs',data:  $inputs);
            print_r($error);
            die('Error');
        }
        return $r_alta;
    }

    public function asignar_propiedad(string $identificador, mixed $propiedades)
    {
        if (!array_key_exists($identificador, $this->keys_selects)) {
            $this->keys_selects[$identificador] = new stdClass();
        }

        foreach ($propiedades as $key => $value) {
            $this->keys_selects[$identificador]->$key = $value;
        }
    }

    public function modifica(bool $header, bool $ws = false, string $breadcrumbs = '', bool $aplica_form = true,
                             bool $muestra_btn = true): array|string
    {
        $base = $this->base();
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar datos',data:  $base,
                header: $header,ws:$ws);
        }

        return $base->template;
    }

    private function base(stdClass $params = new stdClass()): array|stdClass
    {
        $r_modifica =  parent::modifica(header: false,aplica_form:  false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar template',data:  $r_modifica);
        }

        $this->asignar_propiedad(identificador:'cat_sat_forma_pago_id',
            propiedades: ["id_selected"=>$this->row_upd->cat_sat_forma_pago_id]);
        $this->asignar_propiedad(identificador:'cat_sat_metodo_pago_id',
            propiedades: ["id_selected"=>$this->row_upd->cat_sat_metodo_pago_id]);
        $this->asignar_propiedad(identificador:'cat_sat_moneda_id',
            propiedades: ["id_selected"=>$this->row_upd->cat_sat_moneda_id]);
        $this->asignar_propiedad(identificador:'com_tipo_cambio_id',
            propiedades: ["id_selected"=>$this->row_upd->com_tipo_cambio_id]);
        $this->asignar_propiedad(identificador:'cat_sat_uso_cfdi_id',
            propiedades: ["id_selected"=>$this->row_upd->cat_sat_uso_cfdi_id]);
        $this->asignar_propiedad(identificador:'cat_sat_tipo_de_comprobante_id',
            propiedades: ["id_selected"=>$this->row_upd->cat_sat_tipo_de_comprobante_id]);
        $this->asignar_propiedad(identificador:'com_producto_id',
            propiedades: ["id_selected"=>$this->row_upd->com_producto_id]);

        $inputs = $this->genera_inputs(keys_selects: $this->keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar inputs',data:  $inputs);
        }

        $data = new stdClass();
        $data->template = $r_modifica;
        $data->inputs = $inputs;

        return $data;
    }

}
